=== timjogorman/ArabicPropbank/frames/verb.dtd
<!--
Frames File DTD, version 1.1
For use with Arabic frames.

Created 10/15/2002, Scott Cotton
Revised 11/20/2012, Kate Peterson, petka@ldc.upenn.edu
-->

<!--
    A verb is the top level entity. 
    We associate with each verb frame file a set of 'frameset' elements
-->
<!ELEMENT verb (id, (comment | frameset)*)>

<!ELEMENT comment (#PCDATA)>

<!--
    A frameset contains a set of roles and a set of frames

    old version of frameset ordering:
    <!ELEMENT frameset (role,(comment | role)*,frame, (comment | frame)*)>

	edited 20 November 2012: 
	The order of frame, role, and comment elements doesn't matter.
	It is possible to have a frameset with no role or no frame, 
	but there should be at least one role or one frame.
-->
<!ELEMENT frameset (comment*,( (role,  (comment | role | frame )*) |
                               (frame, (comment | role | frame )*)  ))> 

<!--
    Each frameset has an identifier, and associates the verb
    with a verbclass (classid).  Optionally, chinese and english 
    definitions or glosses are allowed. 
	
    Arabic files use edef, but cdef may be an empty string.
	
    edited 20 November 2012: vncls and vntheta may appear but 
    are not relevant to Arabic data, so they'll be empty strings.
    "id" attribute is CDATA now.
-->
<!ATTLIST frameset
    id CDATA  #REQUIRED
    cdef CDATA #IMPLIED
    edef CDATA #IMPLIED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!ELEMENT id (#PCDATA)>
<!-- edited 20 November 2012: vncls and vntheta may appear but 
	 are not relevant to Arabic data -->
<!ELEMENT role EMPTY>
<!ATTLIST role
    argnum (m|0|1|2|3|4|5|6|7|8|9) #REQUIRED
    argrole CDATA #REQUIRED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!--
    A frame consists of a set of tuples of mapping and example elements
	edited 20 Nov 2012: Comments can occur at the end, too, and all comments are optional.
-->
<!ELEMENT frame (((comment|mapping)*)?, example, (comment|example)*) > 

<!--
    A mapping is an ordered list of mapitems, with a verb in there somewhere

    eg

    <mapping>
        <mapitem src="sNP" trg="arg0"/>
        <V/>
        <mapitem src="dNP" trg="arg1"/>
    </mapping>
-->

<!-- edited 20 Nov 2012: Arabic data doesn't use mapping, so mapitem is optional. -->
<!ELEMENT mapping (V*, (mapitem | comment)*)> 
<!ELEMENT mapitem EMPTY>
<!ATTLIST mapitem
    src (sbj|npobj|ipobj|ext|dir|controlip|io|other) #REQUIRED
    trg (arg0|arg1|arg2|arg3|arg4|arg5|argM) #REQUIRED>
<!ELEMENT V EMPTY>

<!--
    finally, an example is completely unstructured, but we may optionally
    specify of source.
	edited 20 Nov 2012: allowing comments to occur at the end, too, and arg is optional.
-->
<!ELEMENT example (parse, (arg|V|comment)*)> 


<!ELEMENT parse (#PCDATA)>
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  g CDATA #IMPLIED>

=== timjogorman/ArabicPropbank/frames/daEA-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>daEA</id>
<comment/>
<frameset cdef="" edef="to request or invite, to supplicate, to pray humbly" id="01" vncls="">
<role argnum="0" argrole="agent making the request" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>انا كنت عاوز ادعو * الكل  للحفلة</parse>
<comment/>
<arg f="" g="I" n="0">* انا</arg>
<arg f="" g="everyone" n="2">الكل</arg>
<arg f="" g="to the party" n="1">للحفلة</arg>
</example>
<comment/>
</frame>
<comment>ARZ</comment>
<role argnum="1" argrole="the request or invitation" vncls="" vntheta=""/>
<role argnum="2" argrole="audience to whom the request or invitation is made" vncls="" vntheta=""/>
</frameset>
<frameset cdef="" edef="to curse" id="02" vncls="">
<role argnum="0" argrole="speaker" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>أنا دعيت * عليك ما تسافرش</parse>
<comment/>
<arg f="" g="I" n="0">* أنا</arg>
<arg f="" g="on you" n="2">عليك</arg>
<arg f="" g="so you will not travel" n="1">ما تسافرش</arg>
</example>
<comment/>
</frame>
<comment>ARZ</comment>
<role argnum="1" argrole="utterance" vncls="" vntheta=""/>
<role argnum="2" argrole="on whom? (marked by على)" vncls="" vntheta=""/>
</frameset>
<frameset cdef="" edef="to pray" id="03" vncls="">
<role argnum="0" argrole="entity praying" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>دعا الراجل ربه أنه يشفيه</parse>
<comment/>
<arg f="" g="the man" n="0">الراجل</arg>
<arg f="" g="his God" n="1">ربه</arg>
<arg f="" g="that he will heal him" n="2">أنه يشفيه</arg>
</example>
<comment/>
</frame>
<comment>ARZ</comment>
<role argnum="1" argrole="to whom (God)" vncls="" vntheta=""/>
<role argnum="2" argrole="for what" vncls="" vntheta=""/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/OaqoraD-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>OaqoraD</id>
    <comment/>
    <frameset cdef="" edef="to lend" id="01">
        <role argnum="0" argrole="lender"/>
        <frame>
            <mapping>
                <comment/>
            </mapping>
            <example>
                <parse>بنك تونس العربي الدولي أقرض عائلة بن علي 350 مليون دينار</parse>
                <comment/>
                <arg f="" g="it" n="0">* &gt;  بنك تونس العربي الدولي</arg>
                <arg f="" g="family of Ben Ali" n="1">عائلة بن علي</arg>
                <arg f="" g="350 million dinars" n="2">350 مليون دينار</arg>
            </example>
            <comment/>
        </frame>
        <comment/>
        <role argnum="1" argrole="lent-to"/>
        <role argnum="2" argrole="thing lent"/>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/damaj-u-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>damaj-u</id>

<frameset cdef="" edef="to merge or unite, to join" id="01" vncls="">
<role argnum="0" argrole="entity uniting" vncls="" vntheta=""/>
<frame>
<mapping>


<comment/>
</mapping>
<example>
<parse>دمج الرسام اللون الأحمر مع الأصفر ببراعة</parse>

<arg f="" g="the artist" n="0">الرسام</arg>
<arg f="" g="the red color" n="1">اللون الأحمر</arg>
<arg f="" g="with the yellow" n="2">مع الأصفر</arg>
<arg f="mnr" g="skillfulness" n="m">ببراعة</arg>

<comment/>
</example>


<comment/>
</frame>

<role argnum="1" argrole="things united" vncls="" vntheta=""/>
<role argnum="2" argrole="with what if separated from Arg1" vncls="" vntheta=""/>

<comment/>
</frameset>
<frameset cdef="" edef="to become dark" id="02" vncls="">
<role argnum="1" argrole="things becoming dark" vncls="" vntheta=""/>
<frame>
<mapping>


<comment/>
</mapping>
<example>
<parse>دمج الليل</parse>

<arg f="" g="the night" n="1">الليل</arg>

<comment/>
</example>


<comment/>
</frame>


<comment/>
</frameset>

<comment/>
</verb>

=== timjogorman/ArabicPropbank/frames/$ahid-a-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>$ahid-a</id>
    <frameset cdef="" edef="to witness, experience" id="01">
        <role argnum="0" argrole="the experiencer"/>
        <role argnum="1" argrole="thing experienced"/>
        <frame>
            <example>
                <parse>
                    (S
                    (CONJ و)
                    (VP
                    (PRT
                    (VERB_PART قد))
                    (PV+PVSUFF_SUBJ:1P شهدنا)
                    (NP-SBJ
                    (-NONE- *))
                    (NP-TMP
                    (NOUN+CASE_DEF_ACC خلال)
                    (NP
                    (DET+NOUN+NSUFF_FEM_DU_GEN السنتين)
                    (DET+ADJ+NSUFF_FEM_DU_GEN الماضيتين)))
                    (NP-OBJ
                    (NP
                    (NOUN+CASE_INDEF_ACC التزاماً)
                    (ADJ+CASE_INDEF_ACC سياسياً)
                    (ADJ+CASE_INDEF_ACC متزايداً))
                    (PP
                    (PREP ب)
                    (NP
                    (DET+NOUN+NSUFF_FEM_SG+CASE_DEF_GEN الصحة))))
                    (PP-LOC
                    (PREP في)
                    (NP
                    (NOUN_QUANT+CASE_DEF_GEN كل)
                    (NP
                    (NOUN+CASE_DEF_GEN انحاء)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN العالم))))))
                    (PUNC .))
                </parse>
                <arg f="" g="we" n="0">*</arg>
                <arg f="tmp" g="during the past 2 years" n="m">خلال السنتين الماضيتين</arg>
                <arg f="" g="an increased interest in health" n="1">التزاماً سياسياً متزايداً بالصحة</arg>
                <arg f="loc" g="all over the world" n="m">في كل انحاء العالم</arg>
            </example>
            <example>
                <parse>
                    (S
                    (CONJ فَ-)
                    (SBAR-ADV
                    (SUB_CONJ -إِذا)
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3FS نَجَحَت)
                    (NP-SBJ
                    (-NONE- *))
                    (PP-CLR
                    (PREP فِي)
                    (NP
                    (NOUN+CASE_DEF_GEN إِعْدادِ)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN الأُسْتاذِ)
                    (DET+ADJ+CASE_DEF_GEN الكَفِيِّ))))
                    (PP
                    (PREP عَلَى)
                    (NP
                    (NP
                    (NOUN+CASE_DEF_GEN كُلِّ)
                    (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN المُسْتَوَياتِ)
                    (DET+ADJ+NSUFF_FEM_SG+CASE_DEF_GEN التَّعْلِيمِيَّةِ)))))))
                    (VP
                    (FUT+IV1P+IV+IVSUFF_MOOD:I سَنَشْهَدُ)
                    (NP-SBJ
                    (-NONE- *))
                    (NP-OBJ
                    (NOUN+NSUFF_FEM_SG+CASE_INDEF_ACC نَهْضَةً))
                    (PP
                    (PREP فِي)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN التَّعْلِيمِ)
                    (DET+ADJ+CASE_DEF_GEN الرَّسْمِيِّ))))
                    (PUNC &amp;quot;)
                    (PUNC .))
                </parse>
                <arg f="" g="we" n="0">*</arg>
                <arg f="" g="a renewal" n="1">نَهْضَةً</arg>
                <arg f="" g="in official education" n="2">فِي التَّعْلِيمِ الرَّسْمِيِّ</arg>
            </example>
        </frame>
    </frameset>
    <frameset cdef="" edef="to confirm or certify" id="02">
        <role argnum="0" argrole="agent, confirmer"/>
        <role argnum="1" argrole="theme, entity certified"/>
        <role argnum="2" argrole="secondary predicate"/>
        <frame>
            <example>
                <parse>
                    ARG1 marked by على
                    
                    يشهد معرض صور لخروتشوف على زعامته المضطربة
                </parse>
                <arg f="" g="a photo gallery of Khrushchev" n="0">معرض صور لخروتشوف</arg>
                <arg f="" g="his troubled leadership" n="1">على زعامته المضطربة</arg>
            </example>
            <example>
                <parse>
                    ARG1 marked by ب
                    
                    كل من يشهد **-1 بـلا اله الا الله مسلم
                </parse>
                <arg f="" g="-NONE- &amp;lt; who" n="0">**-1 &amp;lt; من</arg>
                <arg f="" g="there is no God but Allah" n="1">بـلا اله الا الله</arg>
            </example>
            <example>
                <parse>
                    ARG1 is SBAR
                    شائعات كثيرة أخري هدفها إثارة المسلمين وإثارة الأقباط‏ والواقع يشهد **-1 أن المسلمين والأقباط يعيشون معا في اندماج‏
                </parse>
                <arg f="" g="-NONE- &amp;lt; reality" n="0">**-1 &amp;lt; الواقع</arg>
                <arg f="" g="that the Muslims and the Copts live mixed in together" n="1">أن المسلمين والأقباط يعيشون معا في اندماج‏</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/majomaE-n.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>majomaE</id>
<comment/>
<frameset cdef="" edef="convention or assembly, confluence" id="01" vncls="">
<role argnum="1" argrole="the assmblye" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>لن اتوقف حتى أبلغ مجمع الفن</parse>
<comment/>
<arg f="" g="the art" n="1">الفن</arg>
</example>
<comment/>
</frame>
<comment/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/faDaH-a-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>faDaH-a</id>
<frameset cdef="" edef="to expose" id="01">
<role argnum="0" argrole="the exposer"/>
<role argnum="1" argrole="thing exposed"/>
<frame>
<example>
<parse>
(S
  (CONJ و)
  (VP
    (PV+PVSUFF_SUBJ:3MS هدد)
    (NP-SBJ
      (DET+NOUN+CASE_DEF_NOM الاتحاد))
    (PP-CLR
      (PREP ب)
      (NP
        (NOUN+CASE_DEF_GEN نشر)
        (NP
          (NOUN+CASE_DEF_GEN اسماء)
          (NP
            (NP
              (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN المؤسسات))
            (SBAR
              (WHNP-1
                (-NONE- 0))
              (S
                (VP
                  (DET+ADJ.VN+NSUFF_FEM_SG+CASE_DEF_GEN المتخلفة)
                  (NP-SBJ
                    (-NONE- *T*-1))
                  (PP-CLR
                    (PREP عن)
                    (NP
                      (NOUN+CASE_DEF_GEN تطبيق)
                      (NP
                        (DET+NOUN+CASE_DEF_GEN المرسوم)))))))))))
    (SBAR-PRP
      (PUNC &quot;)
      (SUB_CONJ كي)
      (S
        (VP
          (IV3MS+IV+IVSUFF_MOOD:S يفضح)
          (NP-SBJ
            (-NONE- *))
          (S-NOM-OBJ
            (S-NOM
              (VP
                (NOUN.VN+CASE_DEF_ACC تعدي)
                (NP-SBJ
                  (POSS_PRON_3FS ها))
                (PP-CLR
                  (PREP على)
                  (NP
                    (NOUN+CASE_DEF_GEN حقوق)
                    (NP
                      (DET+NOUN+CASE_DEF_GEN العمال))))))
            (CONJ و)
            (S-NOM
              (VP
                (ADJ.VN+NSUFF_FEM_SG+CASE_DEF_GEN مخالفت)
                (NP-SBJ
                  (POSS_PRON_3FS ها))
                (NP-OBJ
                  (DET+NOUN+CASE_DEF_GEN القوانين)
                  (CONJ و)
                  (DET+NOUN+CASE_DEF_GEN المراسيم)))))))
      (PUNC &quot;)))
  (PUNC .))
</parse>
<arg f="" g="" n="0">-NONE- *</arg>
<arg f="" g="its violation of the workers rights and violations of laws and decrees" n="1">تعديها على حقوق العمال و مخالفتها القوانين و المراسيم</arg>
</example>
</frame>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/EiyAT-n.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>EiyAT</id>
<comment/>
<frameset cdef="" edef="to shout, to yell, to cry" id="01" vncls="">
<role argnum="0" argrole="entity shouting" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>عياط  الأم على أولادها كان واصل لأخر السما</parse>
<comment/>
<arg f="" g="the mother" n="0">الأم</arg>
<arg f="" g="at her kids" n="1">على أولادها</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="on whom" vncls="" vntheta=""/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/$aEar-u-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>$aEar-u</id>
    <frameset cdef="" edef="to feel or be aware of" id="01">
        <role argnum="0" argrole="feeler"/>
        <role argnum="1" argrole="emotion"/>
        <role argnum="2" argrole="entity to or for whom the emotion is directed"/>
        <frame>
            <mapping>
                <V/>
                <mapitem src="sbj" trg="arg0"/>
            </mapping>
            <example>
                <parse>
                    (VP
                    (PRT
                    (FUT_PART س))
                    (IV1S+IV+IVSUFF_MOOD:I أغيب)
                    (NP-SBJ
                    (-NONE- *))
                    (PP-CLR
                    (PREP عن)
                    (NP
                    (NOUN+CASE_DEF_GEN كأس)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN العالم))))))
                    (CONJ و)
                    (S
                    (VP
                    (IV1S+IV+IVSUFF_MOOD:I أشعر)
                    (NP-SBJ
                    (-NONE- *))
                    (PP-CLR
                    (TYPO ي)
                    (NP
                    (NP
                    (NOUN خيبة)
                    (NP
                    (NOUN+CASE_INDEF_GEN أمل)))
                    (ADJP
                    (ADJ+NSUFF_FEM_SG+CASE_INDEF_GEN كبيرة))))))
                </parse>
                <arg f="" g="I" n="0">-NONE- *</arg>
                <arg f="" g="very disappointed" n="1">بخيبة أمل</arg>
            </example>
            <example>
                <parse>
                    (VP
                    (IV3MS+IV+IVSUFF_MOOD:I يشعر)
                    (NP-SBJ
                    (-NONE- *))
                    (SBAR
                    (SUB_CONJ ان)
                    (S
                    (SBAR-NOM-TPC-3
                    (WHNP-1
                    (REL_PRON مَن))
                    (S
                    (VP
                    (PRT
                    (NEG_PART لم))
                    (IV3MS+IV+IVSUFF_MOOD:J ينكسر)
                    (NP-SBJ
                    (-NONE- *T*-1))
                    (PP-TMP
                    (PREP في)
                    (NP
                    (NP
                    (NOUN_QUANT+CASE_DEF_GEN نصف)
                    (NP
                    (NOUN+CASE_INDEF_GEN قرن)))
                    (SBAR
                    (WHNP-2
                    (-NONE- 0))
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3MS مضى)
                    (NP-SBJ
                    (-NONE- *T*-2))))))))))
                    (VP
                    (PRT
                    (NEG_PART لن))
                    (IV3MS+IV+IVSUFF_MOOD:S ينكسر)
                    (NP-SBJ
                    (-NONE- *T*-3))
                    (NP-TMP
                    (DET+NOUN+CASE_DEF_ACC اليوم))))))
                    (PUNC .))
                </parse>
                <arg f="" g="He" n="0">-NONE- *</arg>
                <arg f="" g="that whomever did not break during the past century won't break today" n="1-sbar">ان مَن لم ينكسر في نصف قرن مضى لن ينكسر اليوم</arg>
                <V/>
            </example>
            <example>
                <parse>
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3MS كان)
                    (NP-1
                    (NOUN_PROP شابلن))
                    (VP
                    (IV3MS+IV+IVSUFF_MOOD:I يشعر)
                    (NP-SBJ
                    (-NONE- *T*-1))
                    (NP-ADV
                    (NOUN+CASE_DEF_ACC نحو)
                    (NP
                    (NOUN_PROP هتلر)))
                    (PP-CLR
                    (PREP ب)
                    (NP
                    (NP
                    (DET+NOUN+CASE_DEF_GEN الانجذاب)
                    (CONJ و)
                    (DET+NOUN+CASE_DEF_GEN العداء))
                    (NP-ADV
                    (NOUN+CASE_INDEF_ACC معاً))))))
                    (PUNC .))
                </parse>
                <arg f="" g="NP-SBJ-1" n="0">-NONE- *T*-1&amp;lt;شابلن</arg>
                <arg f="نَحْوَ" g="towards Hitler" n="2">نحو هتلر</arg>
                <arg f="بِ-" g="an attraction and a hatred" n="1">بالانجذاب والعداء</arg>
                <arg f="tmp" g="simultaneously" n="m">معاً</arg>
            </example>
            <example>
                <parse>
                    (NP
                    (DET+NOUN+CASE_DEF_ACC الاحراج))
                    (SBAR
                    (WHNP-1
                    (REL_PRON الذي))
                    (S
                    (VP
                    (IV3FS+IV+IVSUFF_MOOD:I تشعر)
                    (PP-CLR
                    (PREP ب)
                    (NP
                    (NP
                    (PRON_3MS ه))
                    (NP
                    (-NONE- *T*-1))))
                    (NP-SBJ
                    (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_NOM السلطات)
                    (DET+ADJ+NSUFF_FEM_SG+CASE_DEF_NOM اللبنانية))
                    (NP-ADV
                    (NOUN+CASE_DEF_ACC تجاه)
                    (NP
                    (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN السلطات)
                    (DET+ADJ+NSUFF_FEM_SG+CASE_DEF_GEN السورية)))
                    (PP
                    (PREP في)
                    (NP
                    (NOUN+CASE_DEF_GEN موضوع)
                    (NP
                    (DET+NOUN+NSUFF_MASC_PL_GEN المعتقلين))))))))
                    (NP
                    (PRON_3MS هو)))
                    (ADJP-PRD
                    (ADJ_COMP+CASE_DEF_NOM اخف)
                    (NP-ADV
                    (NOUN+NSUFF_FEM_SG+CASE_INDEF_ACC وطأة))
                    (PP
                    (PREP ب)
                    (NP
                    (NOUN+CASE_INDEF_GEN كثير)))
                    (PP
                    (PREP من)
                    (NP
                    (NP
                    (DET+NOUN+CASE_DEF_GEN الاحراج))
                    (NP-ADV
                    (NOUN+CASE_DEF_ACC تجاه)
                    (NP
                    (NP
                    (DET+NOUN+CASE_DEF_GEN الجرح)
                    (DET+ADJ الدامي))
                    (SBAR
                    (WHNP-3
                    (REL_PRON الذي))
                    (S
                    (VP
                    (IV3MS+IV+IVSUFF_MOOD:I يدمي)
                    (NP-SBJ
                    (-NONE- *T*-3))
                    (NP-OBJ
                    (NP
                    (NOUN+CASE_DEF_ACC قلوب))
                    (NP
                    (NP
                    (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN المئات))
                    (PP
                    (PREP من)
                    (NP
                    (DET+NOUN+NSUFF_FEM_PL+CASE_DEF_GEN العائلات)
                    (DET+ADJ+NSUFF_FEM_SG+CASE_DEF_GEN اللبنانية))))))))))))))
                    (PUNC .))
                </parse>
                <arg f="بِ-" g="it" n="1">به</arg>
                <arg f="" g="the Lebanese officials" n="0">السلطات اللبنانية</arg>
                <arg f="تُجاهَ" g="towards the Syrian officials" n="2">تجاه السلطات السورية</arg>
            </example>
        </frame>
    </frameset>
</verb>
