=== timjogorman/ArabicPropbank/frames/verb.dtd
<!--
Frames File DTD, version 1.1
For use with Arabic frames.

Created 10/15/2002, Scott Cotton
Revised 11/20/2012, Kate Peterson, petka@ldc.upenn.edu
-->

<!--
    A verb is the top level entity. 
    We associate with each verb frame file a set of 'frameset' elements
-->
<!ELEMENT verb (id, (comment | frameset)*)>

<!ELEMENT comment (#PCDATA)>

<!--
    A frameset contains a set of roles and a set of frames

    old version of frameset ordering:
    <!ELEMENT frameset (role,(comment | role)*,frame, (comment | frame)*)>

	edited 20 November 2012: 
	The order of frame, role, and comment elements doesn't matter.
	It is possible to have a frameset with no role or no frame, 
	but there should be at least one role or one frame.
-->
<!ELEMENT frameset (comment*,( (role,  (comment | role | frame )*) |
                               (frame, (comment | role | frame )*)  ))> 

<!--
    Each frameset has an identifier, and associates the verb
    with a verbclass (classid).  Optionally, chinese and english 
    definitions or glosses are allowed. 
	
    Arabic files use edef, but cdef may be an empty string.
	
    edited 20 November 2012: vncls and vntheta may appear but 
    are not relevant to Arabic data, so they'll be empty strings.
    "id" attribute is CDATA now.
-->
<!ATTLIST frameset
    id CDATA  #REQUIRED
    cdef CDATA #IMPLIED
    edef CDATA #IMPLIED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!ELEMENT id (#PCDATA)>
<!-- edited 20 November 2012: vncls and vntheta may appear but 
	 are not relevant to Arabic data -->
<!ELEMENT role EMPTY>
<!ATTLIST role
    argnum (m|0|1|2|3|4|5|6|7|8|9) #REQUIRED
    argrole CDATA #REQUIRED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!--
    A frame consists of a set of tuples of mapping and example elements
	edited 20 Nov 2012: Comments can occur at the end, too, and all comments are optional.
-->
<!ELEMENT frame (((comment|mapping)*)?, example, (comment|example)*) > 

<!--
    A mapping is an ordered list of mapitems, with a verb in there somewhere

    eg

    <mapping>
        <mapitem src="sNP" trg="arg0"/>
        <V/>
        <mapitem src="dNP" trg="arg1"/>
    </mapping>
-->

<!-- edited 20 Nov 2012: Arabic data doesn't use mapping, so mapitem is optional. -->
<!ELEMENT mapping (V*, (mapitem | comment)*)> 
<!ELEMENT mapitem EMPTY>
<!ATTLIST mapitem
    src (sbj|npobj|ipobj|ext|dir|controlip|io|other) #REQUIRED
    trg (arg0|arg1|arg2|arg3|arg4|arg5|argM) #REQUIRED>
<!ELEMENT V EMPTY>

<!--
    finally, an example is completely unstructured, but we may optionally
    specify of source.
	edited 20 Nov 2012: allowing comments to occur at the end, too, and arg is optional.
-->
<!ELEMENT example (parse, (arg|V|comment)*)> 


<!ELEMENT parse (#PCDATA)>
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  g CDATA #IMPLIED>

=== timjogorman/ArabicPropbank/frames/mitoSAn-j.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>mitoSAn-j</id>
    <comment/>
    <frameset cdef="" edef="protected, preserved" id="01">
        <role argnum="1" argrole="protected thing"/>
        <frame>
            <mapping>
                <comment/>
            </mapping>
            <example>
                <parse>طب و عربيتى متصانة و بتاع ؟</parse>
                <comment/>
                <arg f="" g="my car" n="0">عربيتى</arg>
            </example>
            <comment/>
        </frame>
        <comment/>
        <role argnum="2" argrole="from what?"/>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/{isotafotaH-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>{isotafotaH</id>

<frameset cdef="" edef="to begin something" id="01" vncls="">
<role argnum="0" argrole="entity starting" vncls="" vntheta=""/>
<frame>
<mapping>

<comment/>
</mapping>
<example>
<parse>استفتح * الجلسة بالذكر الحكيم</parse>

<arg f="" g="he" n="0">*</arg>
<arg f="" g="session" n="1">الجلسة</arg>
<arg f="" g="with the recitation of the Holy Book" n="2">بالذكر الحكيم</arg>
<comment/>
</example>

<comment/>
</frame>

<role argnum="1" argrole="thing started" vncls="" vntheta=""/>
<role argnum="2" argrole="sarting with what" vncls="" vntheta=""/>
<comment/>
</frameset>
<comment/>
</verb>

=== timjogorman/ArabicPropbank/frames/makotuwb-n.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>makotuwb</id>
<frameset cdef="" edef="written" id="01" vncls="">
<role argnum="1" argrole="written thing" vncls="" vntheta=""/>
<role argnum="2" argrole="location" vncls="" vntheta=""/>
<frame>
<example>
<parse>(VP
    (PRT
      (NEG_PART لن))
    (IV1P+IV+IVSUFF_MOOD:S نكون)
    (NP-SBJ
      (-NONE- *))
    (ADJP-PRD
      (ADJ_COMP+CASE_DEF_ACC اقل)
      (NP-ADV
        (NP
          (NOUN غيرة))
        (CONJ و)
        (NP
          (NP
            (NOUN+CASE_INDEF_ACC اندفاعا))
          (PP
            (PREP في)
            (NP
              (NOUN+CASE_DEF_GEN سبيل)
              (NP
                (NP
                  (NOUN+CASE_INDEF_GEN وطن))
                (SBAR
                  (SBAR
                    (WHNP-1
                      (-NONE- 0))
                    (S
                      (NP-SBJ
                        (NOUN+CASE_DEF_NOM عمر)
                        (NP
                          (NP
                            (POSS_PRON_3MS ه))
                          (NP
                            (-NONE- *T*-1))))
                      (NP-PRD
                        (NOUN+CASE_DEF_NOM عمر)
                        (NP
                          (DET+NOUN+CASE_DEF_GEN التاريخ)
                          (DET+ADJ+CASE_DEF_GEN المكتوب)))))</parse>
<arg f="" g="it" n="1">? &lt; التاريخ</arg>
<comment/>
</example>
<comment/>
</frame>
<comment/>
</frameset>
<comment/>
<frameset cdef="" edef="destined, fated" id="02" vncls="">
<role argnum="0" argrole="agent" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>مكتوب علينا الفشل</parse>
<comment/>
<arg f="" g="on us" n="1">علينا</arg>
<arg f="" g="the failure" n="2">الفشل</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="entity destined" vncls="" vntheta=""/>
<role argnum="2" argrole="to what" vncls="" vntheta=""/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/xabuv-i-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>xabuv-i</id>
<comment/>
<frameset cdef="" edef="to be or become malicious or malevolnet" id="01">
<role argnum="1" argrole="entity getting malicious"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>خبث الرجل في سلوكه</parse>
<comment/>
<arg f="" g="the man" n="1">الرجل</arg>
<arg f="" g="in his behavior" n="2">في سلوكه</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="2" argrole="in what"/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/{inoEajaq-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>{inoEajaq</id>
    <comment/>
    <frameset cdef="" edef="to clamor" id="01">
        <role argnum="1" argrole="demander"/>
        <frame>
            <mapping>
                <comment/>
            </mapping>
            <example>
                <parse>انفض المؤتمر الذي انعجقت به بيروت</parse>
                <comment/>
                <arg f="" g="Beirut" n="0">بيروت</arg>
                <arg f="" g="with it" n="1">به</arg>
            </example>
            <comment/>
        </frame>
        <comment/>
        <role argnum="2" argrole="demanded"/>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/OagoDab-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>OagoDab</id>
    <frameset cdef="" edef="to anger, upset" id="01">
        <role argnum="0" argrole="entity causing anger"/>
        <role argnum="1" argrole="angry entity"/>
        <frame>
            <example>
                <parse>
                    (S
                    (NP-SBJ
                    (DET+NOUN+CASE_DEF_NOM الأمر))
                    (SBAR-PRD
                    (WHNP-1
                    (REL_PRON الذي))
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3MS اغضب)
                    (NP-SBJ
                    (-NONE- *T*-1))
                    (NP-OBJ
                    (NOUN والد)
                    (NP
                    (POSS_PRON_1S ي)))
                    (S-ADV
                    (VP
                    (ADJ.VN+CASE_INDEF_ACC قائلاً)
                    (NP-SBJ
                    (-NONE- *-1))
                    (PP
                    (PREP ل)
                    (NP
                    (PRON_3FS ها)))
                    (PUNC :)
                    (S
                    (PUNC &amp;quot;)
                    (S
                    (VP
                    (PRT
                    (NEG_PART لا))
                    (IV1S+IV+IVSUFF_MOOD:I ادري)
                    (NP-SBJ
                    (-NONE- *))
                    (SBAR-ADV
                    (WHADVP-4
                    (INTERROG_ADV لِمَ))
                    (S
                    (VP
                    (IV2FS+IV+IVSUFF_SUBJ:2FS_MOOD:I تصرّين)
                    (NP-SBJ
                    (-NONE- *))
                    (PP-CLR
                    (PREP على)
                    (S-NOM
                    (VP
                    (NOUN.VN+CASE_DEF_GEN ترك)
                    (NP-SBJ
                    (-NONE- *))
                    (NP-OBJ-3
                    (NP
                    (DEM_PRON_MS هذا))
                    (NP
                    (DET+NOUN+CASE_DEF_GEN الطفل)))
                    (S
                    (VP
                    (IV3MS+IV+IVSUFF_MOOD:I يشاهد)
                    (NP-SBJ
                    (-NONE- *-3))
                    (NP-OBJ
                    (NP
                    (DEM_PRON_F هذه))
                    (NP
                    (DET+NOUN+CASE_DEF_ACC الافلام))))))))
                    (ADVP-PRP
                    (-NONE- *T*-4)))))))
                    (PUNC ,)
                    (CONJ ف)
                    (S
                    (NP-TPC-2
                    (PRON_3MS هو))
                    (VP
                    (PRT
                    (NEG_PART لا))
                    (IV3MS+IV+IVSUFF_MOOD:I يضحك)
                    (NP-SBJ
                    (-NONE- *T*-2))))))))))
                    (PUNC -LRB-)
                    (PUNC .)
                    (PUNC .)
                    (PUNC .)
                    (PUNC -RRB-))
                </parse>
                <arg f="" g="" n="0">-NONE- *T*-1</arg>
                <arg f="" g="my father" n="1">والدي</arg>
                <arg f="mnr" g="as he said: &amp;quot;I don't know why you let this child watch these movies&amp;quot;" n="m">&amp;quot; لا ادري لِمَ تصرّين على ترك  هذا الطفل يشاهد 3 هذه الافلام</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/mutawar~iT-j.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>mutawar~iT</id>
    <frameset cdef="" edef="involved" id="01">
        <role argnum="1" argrole="involved entity"/>
        <role argnum="2" argrole="in what (marked by في)"/>
        <frame>
            <example>
                <parse>
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3FS كانت)
                    (NP-PRD
                    (NOUN لدي)
                    (NP
                    (PRON_3MP هم)))
                    (NP-SBJ
                    (NP
                    (NP
                    (NOUN+NSUFF_FEM_SG+CASE_INDEF_NOM ادلة))
                    (PP
                    (PREP على)
                    (SBAR
                    (SUB_CONJ ان)
                    (S
                    (NP-SBJ
                    (NOUN_PROP كوبا))
                    (ADJP-PRD
                    (ADJ+NSUFF_FEM_SG+CASE_INDEF_NOM متورطة)
                    (PP
                    (PREP في)
                    (NP
                    (NP
                    (NOUN+CASE_DEF_GEN تبادل)
                    (NP
                    (NOUN+NSUFF_FEM_PL+CASE_INDEF_GEN معلومات)))
                    (NP-ADV
                    (NOUN+CASE_DEF_ACC مع)
                    (NP
                    (NOUN+NSUFF_FEM_SG+CASE_INDEF_GEN دولة)
                    (ADJ اخرى))))))))))
                </parse>
                <arg f="" g="Cuba" n="1">كوبا</arg>
                <arg f="" g="in exchanging information with another state" n="2">في تبادل معلومات مع دولة اخرى</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/$ar~ib-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd"><verb>
<id>$ar~ib</id>
<comment>EGYPTIAN ARABIC Framefile based on $ar~ab</comment>
<frameset cdef="" edef="to make someone drink" id="01" vncls="">
<role argnum="0" argrole="causer" vncls="" vntheta="" />
<frame>
<mapping>
<comment />
</mapping>
<example>
<parse>بابا كان بيشرب * نا الدوا كل يوم</parse>
<comment />
<arg f="" g="father" n="0">* بابا</arg>
<arg f="" g="us" n="1">نا</arg>
<arg f="" g="the medicine" n="2">الدوا</arg>
</example>
<comment />
</frame>
<comment>Based on roleset $ar~ab.01</comment>
<role argnum="1" argrole="drinker" vncls="" vntheta="" />
<role argnum="2" argrole="things drinked" vncls="" vntheta="" />
</frameset>
</verb>
