=== timjogorman/ArabicPropbank/frames/verb.dtd
<!--
Frames File DTD, version 1.1
For use with Arabic frames.

Created 10/15/2002, Scott Cotton
Revised 11/20/2012, Kate Peterson, petka@ldc.upenn.edu
-->

<!--
    A verb is the top level entity. 
    We associate with each verb frame file a set of 'frameset' elements
-->
<!ELEMENT verb (id, (comment | frameset)*)>

<!ELEMENT comment (#PCDATA)>

<!--
    A frameset contains a set of roles and a set of frames

    old version of frameset ordering:
    <!ELEMENT frameset (role,(comment | role)*,frame, (comment | frame)*)>

	edited 20 November 2012: 
	The order of frame, role, and comment elements doesn't matter.
	It is possible to have a frameset with no role or no frame, 
	but there should be at least one role or one frame.
-->
<!ELEMENT frameset (comment*,( (role,  (comment | role | frame )*) |
                               (frame, (comment | role | frame )*)  ))> 

<!--
    Each frameset has an identifier, and associates the verb
    with a verbclass (classid).  Optionally, chinese and english 
    definitions or glosses are allowed. 
	
    Arabic files use edef, but cdef may be an empty string.
	
    edited 20 November 2012: vncls and vntheta may appear but 
    are not relevant to Arabic data, so they'll be empty strings.
    "id" attribute is CDATA now.
-->
<!ATTLIST frameset
    id CDATA  #REQUIRED
    cdef CDATA #IMPLIED
    edef CDATA #IMPLIED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!ELEMENT id (#PCDATA)>
<!-- edited 20 November 2012: vncls and vntheta may appear but 
	 are not relevant to Arabic data -->
<!ELEMENT role EMPTY>
<!ATTLIST role
    argnum (m|0|1|2|3|4|5|6|7|8|9) #REQUIRED
    argrole CDATA #REQUIRED
	vncls CDATA #IMPLIED
	vntheta CDATA #IMPLIED>

<!--
    A frame consists of a set of tuples of mapping and example elements
	edited 20 Nov 2012: Comments can occur at the end, too, and all comments are optional.
-->
<!ELEMENT frame (((comment|mapping)*)?, example, (comment|example)*) > 

<!--
    A mapping is an ordered list of mapitems, with a verb in there somewhere

    eg

    <mapping>
        <mapitem src="sNP" trg="arg0"/>
        <V/>
        <mapitem src="dNP" trg="arg1"/>
    </mapping>
-->

<!-- edited 20 Nov 2012: Arabic data doesn't use mapping, so mapitem is optional. -->
<!ELEMENT mapping (V*, (mapitem | comment)*)> 
<!ELEMENT mapitem EMPTY>
<!ATTLIST mapitem
    src (sbj|npobj|ipobj|ext|dir|controlip|io|other) #REQUIRED
    trg (arg0|arg1|arg2|arg3|arg4|arg5|argM) #REQUIRED>
<!ELEMENT V EMPTY>

<!--
    finally, an example is completely unstructured, but we may optionally
    specify of source.
	edited 20 Nov 2012: allowing comments to occur at the end, too, and arg is optional.
-->
<!ELEMENT example (parse, (arg|V|comment)*)> 


<!ELEMENT parse (#PCDATA)>
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  g CDATA #IMPLIED>

=== timjogorman/ArabicPropbank/frames/SalaH-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>SalaH</id>
<comment/>
<frameset cdef="" edef="to suit or fit or suitable for" id="01" vncls="">
<role argnum="1" argrole="entity fit" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>هو من يصلح * لهذا المركز</parse>
<comment/>
<arg f="" g="he" n="1">* هو</arg>
<arg f="" g="for this position" n="2">لهذا المركز</arg>
</example>
<comment/>
</frame>
<comment>Egyptian</comment>
<role argnum="2" argrole="for what" vncls="" vntheta=""/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/kAbar-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>kAbar</id>
    <frameset cdef="" edef="to stickle" id="01">
        <role argnum="0" argrole="insister"/>
        <role argnum="1" argrole="thing insisted"/>
        <frame>
            <example>
                <parse>
                    (S
                    (NP-TPC-1
                    (NOUN_QUANT+CASE_DEF_ACC بعض)
                    (NP
                    (DET+NOUN+NSUFF_FEM_SG+CASE_DEF_GEN الانظمة)))
                    (VP
                    (IV3FS+IV+IVSUFF_MOOD:I تفهم)
                    (NP-SBJ
                    (-NONE- *T*-1))
                    (NP-OBJ
                    (IVSUFF_DO:3FS ها))))
                    (CONJ و)
                    (S
                    (VP
                    (IV3FS+IV+IVSUFF_MOOD:I تكابر)
                    (NP-SBJ
                    (-NONE- *))
                    (NP-PRP
                    (NP
                    (NOUN+CASE_INDEF_ACC خوفا))
                    (PP
                    (PREP على)
                    (NP
                    (NP
                    (NOUN+CASE_DEF_GEN كراسي)
                    (NP
                    (POSS_PRON_3FS ها)))
                </parse>
                <arg f="" g="It" n="0">-NONE- *&amp;lt;بعض الانظمة</arg>
                <arg f="cau" g="pecause of Fearing  of ..." n="m">خوفا على كراسيها</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/$araH-a-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>$araH-a</id>
    <frameset cdef="" edef="to explain" id="01">
        <role argnum="0" argrole="the explainer"/>
        <role argnum="1" argrole="the explanation"/>
        <role argnum="2" argrole="the recipient of the explanation"/>
        <frame>
            <example>
                <parse>
                    (S
                    (CONJ و)
                    (VP
                    (PRT
                    (FUT_PART س)
                    (IV3MS+IV+IVSUFF_MOOD:I يظهر)
                    (NP-SBJ
                    (NOUN_PROP بوش)
                    (NP-OBJ
                    (NP
                    (NOUN+CASE_INDEF_ACC تفهماً)
                    (PUNC &amp;quot;)
                    (PP
                    (PREP ل)
                    (NP
                    (NP
                    (DET+NOUN+CASE_DEF_GEN لضغوط)
                    (DET+ADJ+NSUFF_FEM_SG+CASE_DEF_GEN الداخلية)
                    (PP
                    (PREP ل)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN لرأي)
                    (DET+ADJ+CASE_DEF_GEN العام)
                    (DET+ADJ+CASE_DEF_GEN الاسرائيلي)
                    (PUNC ,)
                    (NAC
                    (CONJ و)
                    (S-ADV
                    (VP
                    (PSEUDO_VERB لكن)
                    (NP-SBJ-1
                    (PRON_3MS ه)
                    (S
                    (VP
                    (PRT
                    (FUT_PART س)
                    (IV3MS+IV+IVSUFF_MOOD:I يشرح)
                    (NP-SBJ
                    (-NONE- *-1)
                    (PP
                    (PREP ل)
                    (NP
                    (NOUN_PROP شارون)
                    (NP-OBJ
                    (NOUN+NSUFF_FEM_SG+CASE_DEF_ACC اهمية)
                    (NP
                    (NP
                    (NOUN+CASE_DEF_GEN ضبط)
                    (NP
                    (DET+NOUN+CASE_DEF_GEN النفس)
                    (ADJP
                    (DET+ADJ+CASE_DEF_GEN الاسرائيلي)
                    (PUNC &amp;quot;)
                    (PUNC .)
                </parse>
                <arg f="" g="" n="0">-NONE- *-1&amp;lt;بوش</arg>
                <arg f="" g="to Sharon" n="2">لشارون</arg>
                <arg f="" g="the importance for Israel of self-control" n="1">أهمية ضبط النفس الإسرائيلي</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/muHiyT-n.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>muHiyT</id>
<comment/>
<frameset cdef="" edef="surrounding" id="01">
<role argnum="0" argrole="surrounding entity"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>(S
    (CONJ و)
    (VP
      (PV+PVSUFF_SUBJ:3FS حضت)
      (NP-SBJ
        (-NONE- *))
      (NP-OBJ
        (DET+NOUN+NSUFF_MASC_PL_ACC الاميركيين))
      (PP-MNR
        (PREP ب)
        (NP
          (NOUN+NSUFF_FEM_SG+CASE_INDEF_GEN قوة)))
      (PP-CLR
        (PREP على)
        (NP
          (NOUN+CASE_DEF_GEN تجنب)
          (NP
            (NP
              (DET+NOUN+CASE_DEF_GEN السفر))
            (PP-DIR
              (PREP الى)
              (NP
                (NP
                  (NOUN_PROP ايوديا))
                (CONJ و)
                (NP
                  (NP
                    (NP
                      (DET+NOUN+CASE_DEF_GEN المناطق))
                    (SBAR
                      (WHNP-1
                        (-NONE- 0))
                      (S
                        (VP
                          (DET+ADJ.VN+NSUFF_FEM_SG+CASE_DEF_GEN المحيطة)
                          (NP-SBJ
                            (-NONE- *T*-1))
                          (PP-CLR
                            (PREP ب)
                            (NP
                              (PRON_3FS ها)))))))
                  (PP-LOC
                    (PREP في)
                    (NP
                      (NOUN+NSUFF_FEM_SG+CASE_DEF_GEN ولاية)
                      (NP
                        (NOUN_PROP اوتار)
                        (NOUN_PROP براديش)))))))))))
    (PUNC .)))</parse>
<comment/>
<arg f="" g="they" n="0">-NONE- *T*-1&gt; المناطق</arg>
<arg f="" g="by them" n="1">بها</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="what? (marked by ب)"/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/ta$an~aj-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>ta$an~aj</id>
<comment/>
<frameset cdef="" edef="to suffer from a spasm or cramp" id="01">
<role argnum="0" argrole="things got spasm"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>تشنجت عضلات رقبة أخي</parse>
<comment/>
<arg f="" g="neck muscules" n="1">عضلات رقبة</arg>
<arg f="" g="my brother" n="2">أخي</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="entity affected"/>
</frameset>
<frameset cdef="" edef="to freeze and not able to move (multi word expression)" id="02">
<role argnum="0" argrole="entity freezing"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>تشنج الصبي عند سماعه الخبر المؤلم</parse>
<comment/>
<arg f="" g="the child" n="0">الصبي</arg>
</example>
<comment/>
</frame>
<comment/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/Ou$oEil-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
    <id>Ou$oEil</id>
    <frameset cdef="" edef="light, to set on fire or make lighter" id="01">
        <role argnum="0" argrole="setter"/>
        <role argnum="1" argrole="entity"/>
        <frame>
            <example>
                <parse>
                    (S
                    (S
                    (VP
                    (PV+PVSUFF_SUBJ:3FS انطفأت)
                    (NP-SBJ
                    (DET+NOUN+CASE_DEF_NOM الاضواء))))
                    (CONJ ف)
                    (S
                    (VP
                    (PV_PASS+PVSUFF_SUBJ:3FS أشعلت)
                    (NP-SBJ-2
                    (DET+NOUN+CASE_DEF_NOM الشموع))
                    (NP-OBJ
                    (-NONE- *-2))))
                    (PUNC ,)
                    (CONJ و)
                    (S
                    (NP-TPC-1
                    (NOUN+CASE_INDEF_NOM دموع))
                    (VP
                    (PV+PVSUFF_SUBJ:3FS استمرت)
                    (NP-SBJ
                    (-NONE- *T*-1))
                    (NP-ADV
                    (NOUN+CASE_DEF_ACC نحو)
                    (NP
                    (NOUN_NUM 25)
                    (NP
                    (NOUN+CASE_INDEF_ACC عاماً))))
                    (PUNC -LRB-)
                    (PUNC .)
                    (PUNC .)
                    (PUNC .)
                    (PUNC -RRB-)))
                    (PUNC .))
                </parse>
                <arg f="" g="the candles" n="1">الشموع</arg>
            </example>
        </frame>
    </frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/basaq-u-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>basaq-u</id>
<comment/>
<frameset cdef="" edef="to be hight, to be towering" id="01" vncls="">
<role argnum="1" argrole="entity rising" vncls="" vntheta=""/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>بسق النخل عاليا</parse>
<comment/>
<arg f="" g="the date palm" n="1">النخل</arg>
<arg f="" g="high" n="2">عاليا</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="2" argrole="above what, amount risen" vncls="" vntheta=""/>
</frameset>
</verb>

=== timjogorman/ArabicPropbank/frames/gal~-u-v.xml
<!DOCTYPE verb SYSTEM "verb.dtd">
<verb>
<id>gal~-u</id>
<comment/>
<frameset cdef="" edef="to handcuff or chain" id="01">
<role argnum="0" argrole="entity chaining"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل * يديه و قدميه بقيود من حديد</parse>
<comment/>
<arg f="" g="NONE" n="0">*? NONE</arg>
<arg f="" g="with iron chains" n="1">بقيود من حديد</arg>
<arg f="" g="his hands and his feet" n="2">يديه و قدميه</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="with what"/>
<role argnum="2" argrole="chained entity"/>
</frameset>
<frameset cdef="" edef="to betray , to be unfair" id="02">
<role argnum="0" argrole="entity betraying"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل الرجل اخوته في حصتهم</parse>
<comment/>
<arg f="" g="the man" n="0">الرجل</arg>
<arg f="" g="in their share" n="1">في حصتهم</arg>
<arg f="" g="his brothers" n="2">اخوته</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="in what"/>
<role argnum="2" argrole="beneficiary"/>
</frameset>
<frameset cdef="" edef="to intervene, to go between" id="03">
<role argnum="1" argrole="entity going between"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل الماء بين الأشجار</parse>
<comment/>
<arg f="" g="the water" n="1">الماء</arg>
<arg f="" g="between the trees" n="2">بين الأشجار</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="2" argrole="between what"/>
</frameset>
<frameset cdef="" edef="to be thirsty" id="04">
<role argnum="1" argrole="entity being thirsty"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل الولد</parse>
<comment/>
<arg f="" g="the boy" n="1">الولد</arg>
</example>
<comment/>
</frame>
<comment/>
</frameset>
<frameset cdef="" edef="to enter in" id="05">
<role argnum="0" argrole="entity entering"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل * في البلاد</parse>
<comment/>
<arg f="" g="NONE" n="0">*? NONE</arg>
<arg f="" g="in the country" n="1">في البلاد</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="where"/>
</frameset>
<frameset cdef="" edef="to hate, to bear grudge against" id="06">
<role argnum="0" argrole="entity hating (idiomatic)"/>
<frame>
<mapping>
<comment/>
</mapping>
<example>
<parse>غل صدره  على أعدائه</parse>
<comment/>
<arg f="" g="NONE" n="0">NONE</arg>
<arg f="" g="on his enemies" n="1">على أعدائه</arg>
</example>
<comment/>
</frame>
<comment/>
<role argnum="1" argrole="hated one"/>
</frameset>
</verb>
